<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Adicionales_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function listar(){
        $this->db->order_by('adicionalId', 'desc');
        return $this->db->get('adicionales')->result_array();
    }


   
    function listar_adicionales_por_docente($docenteId){
      $this->db->select("adi.*");
      $this->db->from("adicionales adi");
      $this->db->where("adi.docentes_docenteId ='{$docenteId}' ");
      return $this->db->get()->row_array();
    }

    function check_if_exists($key)
    {

        $query =  $this->db->get_where('adicionales',array('docentes_docenteId'=>$key));

        if ($query->num_rows() > 0){
            return true;
        } else{
            return false;
        }
    }

    /*
     * function to add new 
    */
    function agregar($params)
    {
        $this->db->insert('adicionales',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar($params, $docenteId)
    {

        if($this->check_if_exists($docenteId)){
            $this->db->where("docentes_docenteId", $docenteId);
            return $this->db->update("adicionales" ,$params);
        }else{
            return $this->agregar($params);
        }
            
    }

    /*
     * function to delete plato
     */
    function eliminar($adicionalId)
    {
        return $this->db->delete('adicionales',array('adicionalId'=>$adicionalId));
    }


}

?>