<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Asesoria_Tesis_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }


    /*
     * Get all
    */
    function get_all_asesoria_tesis(){
        $this->db->order_by('tesisId', 'desc');
        return $this->db->get('asesoria_tesis')->result_array();
    }

    /*
     * Get by id
    */
    function get_asesoria_tesis_by_id($tesisId){
        $this->db->select("ase.*");
        $this->db->from("asesoria_tesis ase");
        $this->db->where(" ase.tesisId ='{$tesisId}' ");
        return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_asesoria_tesis($params)
    {
        $this->db->insert('uap_docentes',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_asesoria_tesis($tesisId,$params)
    {
        $this->db->where('tesisId',$tesisId);
        return $this->db->update('asesoria_tesis',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_asesoria_tesis($tesisId)
    {
        return $this->db->delete('uap_docentes',array('tesisId'=>$tesisId));
    }


}

?>