<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Cargos_Academicos_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_cargos_academicos(){
        $this->db->order_by('cargosId', 'desc');
        return $this->db->get('asesoria_tesis')->result_array();
    }


    /*
     * Get by id
    */
   
    function get_cargos_academicos_by_id($cargosId){
      $this->db->select("car.*");
      $this->db->from("cargos_academicos car");
      $this->db->where(" car.cargosId ='{$cargosId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_cargos_academicos($params)
    {
        $this->db->insert('cargos_academicos',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_cargos_academicos($cargosId,$params)
    {
        $this->db->where('cargosId',$cargosId);
        return $this->db->update('cargos_academicos',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_cargos_academicos($cargosId)
    {
        return $this->db->delete('cargos_academicos',array('cargosId'=>$cargosId));
    }


}

?>