<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Convocatorias_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_convocatorias(){

        $records = array();

        $this->db->select("conv.*, sed.*");
        $this->db->from("convocatorias conv");
        $this->db->join('sedes sed', 'sed.sedeId = conv.sedes_sedeId', 'inner');  
        $this->db->order_by('convocatoriaId', 'desc');      
        $query = $this->db->get();

        $records['iTotalRecords'] = $query->num_rows();
        $records['iTotalDisplayRecords'] = $query->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $query->result_array();

        return $records;


    }


    /*
     * Get by id
    */
   
    function get_convocatorias_by_id($convocatoriaId){
      $this->db->select("conv.*");
      $this->db->from("convocatorias conv");
      $this->db->where("conv.convocatoriaId ='{$convocatoriaId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_convocatorias($params)
    {
        $this->db->insert('convocatorias',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_convocatorias($convocatoriaId,$params)
    {
        $this->db->where('convocatoriaId',$convocatoriaId);
        return $this->db->update('convocatorias',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_convocatorias($convocatoriaId)
    {
        return $this->db->delete('convocatorias',array('convocatoriaId'=>$convocatoriaId));
    }


}

?>