<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Convocatorias_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_convocatorias(){
        $this->db->order_by('convocatoriaId', 'desc');
        return $this->db->get('convocatorias')->result_array();
    }


    /*
     * Get by id
    */
   
    function get_convocatorias_by_id($convocatoriaId){
      $this->db->select("conv.*");
      $this->db->from("convocatorias conv");
      $this->db->where("conv.convocatoriaId ='{$convocatoriaId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_convocatorias($params)
    {
        $this->db->insert('convocatorias',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_convocatorias($convocatoriaId,$params)
    {
        $this->db->where('convocatoriaId',$convocatoriaId);
        return $this->db->update('convocatorias',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_convocatorias($convocatoriaId)
    {
        return $this->db->delete('convocatorias',array('convocatoriaId'=>$convocatoriaId));
    }


}

?>