<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Cursos_Escuelas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

   
    function agregar_cursos_x_escuela($params)
    {
        $this->db->insert('cursos_x_escuela',$params);
        return $this->db->insert_id();
    }



     function eliminar_curso_x_escuelas($cursos_cursoId, $escuelas_escuelaId)
    {
        $result =  $this->db->delete('cursos_x_escuela',array('cursos_cursoId'=>$cursos_cursoId, 'escuelas_escuelaId'=>$escuelas_escuelaId));

        if($result){
          return $result;
        }else{
          return $this->db->error();
        }

    }


}

?>