<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Cursos_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_cursos(){

        //

        $records = array();
        //$records['data'] = array();


        /*$this->db->select("esc.*, sed.sedeNombre");
        $this->db->from("escuelas esc, sedes sed");
        $this->db->where("esc.sedes_sedeId = sed.sedeId");*/

        $this->db->select("cur.*");
        $this->db->from("cursos cur");
        $this->db->order_by('cur.cursoNombre', 'asc');
        //$this->db->join('sedes sed', 'sed.sedeId = esc.sedes_sedeId', 'left');
        //$this->db->where("esc.sedes_sedeId = sed.sedeId");
        //$this->db->join('sedes sed', 'sed.sedeId = esc.sedes_sedeId', 'inner');
        //$this->db->where("esc.cursoId ='{$cursoId}' ");
        
        $query = $this->db->get();

        $records['iTotalRecords'] = $query->num_rows();
        $records['iTotalDisplayRecords'] = $query->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $query->result_array();

        return $records;

    }

    function get_all_cursos_select(){

        $records = array();

        $this->db->select("cursoId as id, cursoNombre as text");
        $this->db->from("cursos");
        $this->db->order_by('cursoNombre', 'asc');
        
        //$records['results'] = $this->db->get()->result_array();

        return $this->db->get()->result_array();

    }

    /*
     * Get by id
    */
   
    function get_curso_by_id($cursoId){
      $this->db->select("esc.*");
      $this->db->from("escuelas esc");
      $this->db->where("esc.cursoId ='{$cursoId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_cursos($params)
    {
        $this->db->insert('escuelas',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_cursos($cursoId,$params)
    {
        $this->db->where('cursoId',$cursoId);
        return $this->db->update('escuelas',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_cursos($cursoId)
    {
        return $this->db->delete('escuelas',array('cursoId'=>$cursoId));
    }


}

?>