<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

  class Departamento_model extends CI_Model
  {
      function __construct()
      {
          parent::__construct();
      }

      /*
       * Get all
      */
      function get_all_departamentos(){
          $this->db->order_by('idDepa', 'asc');
          return $this->db->get('ubdepartamento')->result_array();
      }

      /*
       * Get by id
      */
     
      /*function get_idiomas_by_id($idiomaId){
        $this->db->select("idi.*");
        $this->db->from("idiomas idi");
        $this->db->where("idi.idiomaId ='{$idiomaId}' ");
        return $this->db->get()->row_array();
      }*/

  }

?>