<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Estudios_Complementarios_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_estudios_complementarios(){
        $this->db->order_by('estudiosId', 'desc');
        return $this->db->get('estudios_complementarios')->result_array();
    }

    


    function get_estudios_complementarios_by_id($estudiosId){
        $this->db->select("estu.*");
        $this->db->from("estudios_complementarios estu");
        $this->db->where("estu.estudiosId ='{$estudiosId}' ");
        return $this->db->get()->row_array();
    }

 
    function agregar_estudios_complementarios($params)
    {
        $this->db->insert('estudios_complementarios',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_estudios_complementarios($estudiosId,$params)
    {
        $this->db->where('estudiosId',$estudiosId);
        return $this->db->update('estudios_complementarios',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_estudios_complementarios($estudiosId)
    {
        return $this->db->delete('estudios_complementarios',array('estudiosId'=>$estudiosId));
    }


}

?>