<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Experiencia_Profesional_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function listar_por_docente($docenteId){


        $records = array();


        $this->db->select("exp.especializacionId, 
                           exp.docenteId,
                           exp.especInstitucion,
                           exp.especTipoInstitucion,
                           exp.especCargo,
                           DATE_FORMAT(exp.especFecInicio, '%d/%m/%Y') as especFecInicio,
                           DATE_FORMAT(exp.especFecFin, '%d/%m/%Y') as especFecFin,
                           exp.especHastaFecha");

        $this->db->from("experiencia_especializacion exp");
        $this->db->where("exp.docenteId ='{$docenteId}' ");
        $query = $this->db->get();


        $records['iTotalRecords'] = $query->num_rows();
        $records['iTotalDisplayRecords'] = $query->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $query->result_array();

        return $records;

    }


    /*
     * Get by id
    */
   
    function get_experiencia_especializacion_by_id($especializacionId){
      $this->db->select("expdoc.*");
      $this->db->from("experiencia_especializacion expdoc");
      $this->db->where("expdoc.especializacionId ='{$especializacionId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_experiencia_profesional($params)
    {
        $this->db->insert('experiencia_especializacion',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_experiencia_profesional($especializacionId,$params)
    {
        $this->db->where('especializacionId',$especializacionId);
        return $this->db->update('experiencia_especializacion',$params);
    }

    /*
     * function to delete plato
     */
    function eliminar_experiencia_profesional($especializacionId)
    {
        return $this->db->delete('experiencia_especializacion',array('especializacionId'=>$especializacionId));
    }


}

?>