<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Experiencia_Docencia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function listar_por_docente($docenteId){


        $records = array();

        $this->db->select("exp.experienciaId, 
                           exp.docenteId,
                           exp.expDocInstitucion,
                           exp.cargoDocencia,
                           exp.tipoConDocencia,
                           DATE_FORMAT(exp.expDocFecInicio, '%d/%m/%Y') as expDocFecInicio,
                           DATE_FORMAT(exp.expDocFecFin, '%d/%m/%Y') as expDocFecFin,
                           exp.expDocHastaActual");
        $this->db->from("experiencia_docencia exp");
        $this->db->where("exp.docenteId ='{$docenteId}' ");
        $query = $this->db->get();


        $records['iTotalRecords'] = $query->num_rows();
        $records['iTotalDisplayRecords'] = $query->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $query->result_array();

        return $records;

    }

    /*
     * Get all
    */
    function get_all_experiencia_docencia(){
        $this->db->order_by('experienciaId', 'desc');
        return $this->db->get('experiencia_docencia')->result_array();
    }


    /*
     * Get by id
    */
   
    function get_experiencia_docencia_by_id($experienciaId){
      $this->db->select("expdoc.*");
      $this->db->from("experiencia_docencia expdoc");
      $this->db->where("expdoc.experienciaId ='{$experienciaId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_experiencia_docencia($params)
    {
        $this->db->insert('experiencia_docencia',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_experiencia_docencia($experienciaId,$params)
    {
        $this->db->where('experienciaId',$experienciaId);
        return $this->db->update('experiencia_docencia',$params);
    }

    /*
     * function to delete plato
     */
    function eliminar_experiencia_docencia($experienciaId)
    {
        return $this->db->delete('experiencia_docencia',array('experienciaId'=>$experienciaId));
    }


}

?>