<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Facultades_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }


    function get_all_facultades(){

        $records = array();

        $this->db->select("fa.*");
        $this->db->from("facultades fa");
        //$this->db->join('sedes sed', 'sed.sedeId = esc.sedes_sedeId', 'inner');        
        $query = $this->db->get();

        $records['iTotalRecords'] = $query->num_rows();
        $records['iTotalDisplayRecords'] = $query->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $query->result_array();

        return $records;

    }

    function get_all_facultades_select(){

        $records = array();

        $this->db->select("facultadId as id, facultadNombre as text");
        $this->db->from("facultades");
        $this->db->order_by('facultadNombre', 'asc');
        
        //$records['results'] = $this->db->get()->result_array();

        return $this->db->get()->result_array();

    }

    /*
     * Get by id
    */
   
    function get_facultad_by_id($facultadId){

      //CONSULTO LA ESCUELA POR ID
      $this->db->select("esc.*");
      $this->db->from("facultades esc");
      $this->db->where("esc.facultadId ='{$facultadId}' ");
      $records = $this->db->get()->row_array();


      //CONSULTO LOS CURSOS CREADOS PARA LA ESCUELA
      $this->db->select("cxe.cursos_cursoId as id");
      $this->db->from("cursos_x_escuela cxe");
      $this->db->where("cxe.facultades_facultadId ='{$facultadId}' ");
      $cursos = $this->db->get()->result_array();

      $records['cursos'] = $cursos;

      return $records;
      
    }


    function agregar_facultades($params)
    {
        $this->db->insert('facultades',$params);
        return $this->db->insert_id();
    }

    function editar_facultades($facultadId,$params)
    {
        $this->db->where('facultadId',$facultadId);
        return $this->db->update('facultades',$params);
    }

    function eliminar_facultades($facultadId)
    {
        return $this->db->delete('facultades',array('facultadId'=>$facultadId));
    }


}

?>