<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Formaciones_Academicas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_formaciones_academicas(){
        $this->db->order_by('formacionId', 'desc');
        return $this->db->get('formaciones_academicas')->result_array();
    }

    /*
     * Get by id
    */
   
    function get_formaciones_academicas_by_id($formacionId){
      $this->db->select("foracad.*");
      $this->db->from("formaciones_academicas foracad");
      $this->db->where("foracad.formacionId ='{$formacionId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_formaciones_academicas($params)
    {
        $this->db->insert('formaciones_academicas',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_formaciones_academicas($formacionId,$params)
    {
        $this->db->where('formacionId',$formacionId);
        return $this->db->update('formaciones_academicas',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_formaciones_academicas($formacionId)
    {
        return $this->db->delete('formaciones_academicas',array('formacionId'=>$formacionId));
    }


}

?>