<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Herramientas_Informaticas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_herramientas_informaticas(){
        $this->db->order_by('informaticaId', 'desc');
        return $this->db->get('herramientas_informaticas')->result_array();
    }

    function listar_por_docente($docenteId){


        $records = array();

        $this->db->select("herr.informaticaId, 
                           herr.docenteId,
                           herr.inforEspecialidadCurso,
                           herr.inforCentroEstudio,
                           herr.inforNivel,
                           DATE_FORMAT(herr.inforFechaCertificacion, '%d/%m/%Y') as inforFechaCertificacion,
                           herr.inforRutaArchivoCertificacion");
        $this->db->from("herramientas_informaticas herr");
        $this->db->where("herr.docenteId ='20' ");
        $query = $this->db->get();


        $records['iTotalRecords'] = $query->num_rows();
        $records['iTotalDisplayRecords'] = $query->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $query->result_array();

        return $records;

    }

    /*
     * Get by id
    */
   
    function get_herramientas_informaticas_by_id($informaticaId){
      $this->db->select("herrinfo.*");
      $this->db->from("herramientas_informaticas herrinfo");
      $this->db->where("herrinfo.informaticaId ='{$informaticaId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_herramientas_informaticas($params)
    {
        $this->db->insert('herramientas_informaticas',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_herramientas_informaticas($informaticaId,$params)
    {
        $this->db->where('informaticaId',$informaticaId);
        return $this->db->update('herramientas_informaticas',$params);
    }

    /*
     * function to delete plato
     */
    function eliminar_herramientas_informaticas($informaticaId)
    {
        return $this->db->delete('herramientas_informaticas',array('informaticaId'=>$informaticaId));
    }


}

?>