<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Idiomas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_idiomas(){
        $this->db->order_by('idiomaId', 'desc');
        return $this->db->get('idiomas')->result_array();
    }

    function listar_por_docente($docenteId){


        $records = array();

        $this->db->select("idi.idiomaId, 
                           idi.docenteId,
                           idi.idioNombre,
                           idi.idioCentroEstudios,
                           idi.idioNivel,
                           DATE_FORMAT(idi.idioFechaCertificacion, '%d/%m/%Y') as idioFechaCertificacion,
                           idi.idioRutaArchivoCertificacion");
        $this->db->from("idiomas idi");
        $this->db->where("idi.docenteId = {$docenteId} ");
        $query = $this->db->get();


        $records['iTotalRecords'] = $query->num_rows();
        $records['iTotalDisplayRecords'] = $query->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $query->result_array();

        return $records;

    }

    /*
     * Get by id
    */
   
    function get_idiomas_by_id($idiomaId){
      $this->db->select("idi.*");
      $this->db->from("idiomas idi");
      $this->db->where("idi.idiomaId ='{$idiomaId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_idiomas($params)
    {
        $this->db->insert('idiomas',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_idiomas($idiomaId,$params)
    {
        $this->db->where('idiomaId',$idiomaId);
        return $this->db->update('idiomas',$params);
    }

    /*
     * function to delete plato
     */
    function eliminar_idiomas($idiomaId)
    {
        return $this->db->delete('idiomas',array('idiomaId'=>$idiomaId));
    }


}

?>