<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Indicadores_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function listar(){
        $this->db->order_by('indicadorId', 'desc');
        return $this->db->get('indicadores')->result_array();
    }

    /*
     * Get by id
    */
   
    function listar_indicadores_por_docente($docenteId){
      $this->db->select("indi.*");
      $this->db->from("indicadores indi");
      $this->db->where("indi.docentes_docenteId ='{$docenteId}' ");
      return $this->db->get()->row_array();
    }

    function check_if_exists($key)
    {

        $query =  $this->db->get_where('indicadores',array('docentes_docenteId'=>$key));

        if ($query->num_rows() > 0){
            return true;
        } else{
            return false;
        }
    }

    /*
     * function to add new 
    */
    function agregar($params)
    {
        $this->db->insert('indicadores',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar($params, $docenteId)
    {

        if($this->check_if_exists($docenteId)){
            $this->db->where("docentes_docenteId", $docenteId);
            return $this->db->update("indicadores" ,$params);
        }else{
            return $this->agregar($params);
        }
            
    }

    /*
     * function to delete plato
     */
    function eliminar($indicadorId)
    {
        return $this->db->delete('indicadores',array('indicadorId'=>$indicadorId));
    }


}

?>