<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Investigaciones_Publicaciones_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_investigaciones(){
        $this->db->order_by('investigacionesId', 'desc');
        return $this->db->get('investigaciones_publicaciones')->result_array();
    }

    function listar_por_docente($docenteId){


        $records = array();

        $this->db->select("inv.*");
        $this->db->from("investigaciones_publicaciones inv");
        $this->db->where("inv.docenteId ='{$docenteId}' ");
        $query = $this->db->get();

        $records['iTotalRecords'] = $query->num_rows();
        $records['iTotalDisplayRecords'] = $query->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $query->result_array();

        return $records;

    }

    /*
     * Get by id
    */
   
    function get_investigaciones_by_id($investigacionesId){
      $this->db->select("idi.*");
      $this->db->from("investigaciones_publicaciones idi");
      $this->db->where("idi.investigacionesId ='{$investigacionesId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_investigaciones($params)
    {
        $this->db->insert('investigaciones_publicaciones',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_investigaciones($investigacionesId,$params)
    {
        $this->db->where('investigacionesId',$investigacionesId);
        return $this->db->update('investigaciones_publicaciones',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_investigaciones($investigacionesId)
    {
        return $this->db->delete('investigaciones_publicaciones',array('investigacionesId'=>$investigacionesId));
    }


}

?>