<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

  class Provincia_model extends CI_Model
  {
      function __construct()
      {
          parent::__construct();
      }

      function get_provincia_by_departamento($idDepa){

          $this->db->select("prov.*");
          $this->db->from("ubprovincia prov");
          $this->db->where("prov.idDepa ='{$idDepa}' ");
          $this->db->order_by('prov.idDepa', 'asc');
          return $this->db->get()->result_array();
      }



  }

?>