<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Registro_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

  
    function check_if_exists($table, $primarykey, $value)
    {

        $query =  $this->db->get_where($table,array($primarykey=>$value));

        if ($query->num_rows() > 0){
            return true;
        } else{
            return false;
        }
    }

    function randomRepeaterID($length = 8) {
        $characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }


}

?>