<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Sedes_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_sedes(){
        $this->db->order_by('sedeId', 'desc');
        return $this->db->get('sedes')->result_array();
    }

    /*
     * Get by id
    */
   
    function get_sedes_by_id($sedeId){
      $this->db->select("sed.*");
      $this->db->from("sedes sed");
      $this->db->where("sed.sedeId ='{$sedeId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_sedes($params)
    {
        $this->db->insert('sedes',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_sedes($sedeId,$params)
    {
        $this->db->where('sedeId',$sedeId);
        return $this->db->update('sedes',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_sedes($sedeId)
    {
        return $this->db->delete('sedes',array('sedeId'=>$sedeId));
    }


}

?>