<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Sedes_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_sedes(){

        $this->db->order_by('sedeId', 'asc');

        $records = array();
        //$records['data'] = array();

        $records['iTotalRecords'] = $this->db->get('sedes')->num_rows();
        $records['iTotalDisplayRecords'] = $this->db->get('sedes')->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $this->db->get('sedes')->result_array();



        return $records;

    }

    function get_all_sedes_select(){

        $records = array();

        $this->db->select("sedeId as id, sedeNombre as text");
        $this->db->from("sedes");
        $this->db->order_by('sedeNombre', 'asc');
        
        //$records['results'] = $this->db->get()->result_array();

        return $this->db->get()->result_array();

    }

    /*
     * Get by id
    */
   
    function get_sedes_by_id($sedeId){
      $this->db->select("sed.*");
      $this->db->from("sedes sed");
      $this->db->where("sed.sedeId ='{$sedeId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_sedes($params)
    {
        $this->db->insert('sedes',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_sedes($sedeId,$params)
    {
        $this->db->where('sedeId',$sedeId);
        return $this->db->update('sedes',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_sedes($sedeId)
    {
        return $this->db->delete('sedes',array('sedeId'=>$sedeId));
    }


}

?>