<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Tipos_Roles_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_tipo_roles(){
        $this->db->order_by('tipoRolId', 'desc');
        return $this->db->get('tipo_roles')->result_array();
    }

    /*
     * Get by id
    */
   
    function get_tipo_roles_by_id($tipoRolId){
      $this->db->select("tirol.*");
      $this->db->from("tipo_roles tirol");
      $this->db->where("tirol.tipoRolId ='{$tipoRolId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_tipo_roles($params)
    {
        $this->db->insert('tipo_roles',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_tipo_roles($tipoRolId,$params)
    {
        $this->db->where('tipoRolId',$tipoRolId);
        return $this->db->update('tipo_roles',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_tipo_roles($tipoRolId)
    {
        return $this->db->delete('tipo_roles',array('tipoRolId'=>$tipoRolId));
    }


}

?>