<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Usuarios_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get all
    */
    function get_all_usuarios(){


        $records = array();

        $this->db->select("usu.*, sed.sedeNombre");
        $this->db->from("usuarios usu");
        $this->db->join('sedes sed', 'sed.sedeId = usu.sedes_sedeId', 'inner');   
        $this->db->order_by('usuarioId', 'desc');     
        $query = $this->db->get();

        $records['iTotalRecords'] = $query->num_rows();
        $records['iTotalDisplayRecords'] = $query->num_rows();
        $records['sEcho'] = 0;
        $records['sColumns'] = 0;
        $records['aaData'] = $query->result_array();

        return $records;
    
    }

    /*
     * Get by id
    */
   
    function get_usuarios_by_id($usuarioId){
      $this->db->select("usu.*");
      $this->db->from("usuarios usu");
      $this->db->where("usu.usuarioId ='{$usuarioId}' ");
      return $this->db->get()->row_array();
    }

    /*
     * function to add new 
    */
    function agregar_usuarios($params)
    {
        $this->db->insert('usuarios',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update 
    */
    function actualizar_usuarios($usuarioId,$params)
    {
        $this->db->where('usuarioId',$usuarioId);
        return $this->db->update('usuarios',$params);
    }

    /*
     * function to delete plato
     */
    function borrar_usuarios($usuarioId)
    {
        return $this->db->delete('usuarios',array('usuarioId'=>$usuarioId));
    }


}

?>